#!/usr/bin/env bash

# `git show` a fuzzy-selected commit or sequence of commits
#
# Usage:
#
#   git show [git ref]

if [[ $# -ne 0 ]]; then
    git show --pretty=fuller "${@}"
    exit 0
fi

commit_shas="$(git-select-sha)"

if [[ -z "$commit_shas" ]]; then
    exit 0
fi

for sha in $commit_shas; do
    git show --pretty=fuller "$sha"
done
