#!/usr/bin/env bash

# Create a new branch with an upstream
#
# $ git create-branch-with-remote feature1

set -e

name="$*"
branch="${name// /-}"

if [[ -z "$branch" ]]; then
  echo "branch name required." 1>&2
  exit 1
fi

echo git push origin HEAD:refs/heads/"$branch"
git push origin HEAD:refs/heads/"$branch"

echo git fetch origin
git fetch origin

echo git checkout --track -b "$branch" origin/"$branch"
git checkout --track -b "$branch" origin/"$branch"
