#!/usr/bin/env bash

# Checkout commits with fuzzy-selection
#
# Dependencies:
#   fzf

# fuzzy-select a SHA
commit_sha="$(git-select-sha --no-multi)"

if [[ ! -z "$commit_sha" ]]; then
  git checkout "$commit_sha"
fi
