#!/usr/bin/env bash

# Commit with message if passed arguments, else open an editor
#
# Usage:
#   git commit-quick [A brief commit message]

if [[ $# -gt 0 ]]; then
  git commit -m "$*"
else
  git commit -v
fi
