#!/usr/bin/env bash

# Commit with message if passed arguments, else open an editor
#
# Usage:
#   git commit-quick-force [A brief commit message]

if [[ $# -gt 0 ]]; then
  git commit --no-verify -m "$*"
else
  git commit --no-verify -v
fi
