#!/usr/bin/env bash

# `git rebase -i` with a fuzzy-selected target commit
# Begins rebase from the parent of the selected commit
#
# Usage:
#   git rebase-interactive

# fuzzy-select a SHA
commit_sha="$(git-select-sha --no-multi)"

if [[ ! -z "$commit_sha" ]]; then
  git rebase -i "$commit_sha"^
fi
