#!/usr/bin/env bash

# fuzzy-select a git submodule to remove and remove it
#
# Usage:
#   git submodule-rm

set -e

if [[ ! -d .git || ! -f .gitmodules ]]; then
  echo "Error: Must be run from a Git repository root."
  exit 1
fi

IFS=$'\n'

git stash

for submodule in $(git submodule status | awk '{ print $2 }' | fzf --multi); do
  git submodule deinit "${submodule}"
  git rm -f "${submodule}"
  rm -rf "./.git/modules/${submodule}"
  git commit -m "Removed submodule ${submodule}"
done

git stash pop

git status -s --show-stash
