#!/usr/bin/env bash

# Commit staged changes, marking them to be squashed into another commit, which
# is fuzzy-selected
#
# Usage:
#   git commit-squash

# fuzzy-select a SHA
commit_sha="$(git-select-sha --no-multi)"

if [[ ! -z $commit_sha ]]; then
  git commit --squash "$commit_sha"
fi
