#!/usr/bin/env bash

# Deletes branches that are listed in git branch --merged.
#
# $ git delete-merged-branches
# Deleted feature/themes (was c029ab3).
# Deleted feature/live_preview (was a81b002).
# Deleted feature/dashboard (was 923befa).

git branch --no-color --merged |\
  grep -v "\*" |\
  grep -v master |\
  grep -v svn |\
  xargs -n 1 git branch -d
