#!/usr/bin/env bash

# WIP.
# source:
# http://naleid.com/blog/2012/01/17/finding-and-purging-big-files-from-git-history

git gc

git rev-list --objects --all | sort -k 2 > allfileshas.txt

git verify-pack -v .git/objects/pack/pack-*.idx |\
  egrep "^\w+ blob\W+[0-9]+ [0-9]+ [0-9]+$" |\
  sort -k 3 -n -r > bigobjects.txt

for sha in `cut -f 1 -d\  < bigobjects.txt`; do
  long_sha="$(grep "$sha" bigobjects.txt)"

  echo "${long_sha:0:7}" "$(grep "$sha" allfileshas.txt)" |\
    awk '{print $1,$3,$7}' >> "$HOME"/Desktop/bigtosmall.txt
done;

rm -f bigobjects.txt allfileshas.txt
