#!/usr/bin/env bash

# Delete submodule `name`:
#
# $ git delete-submodule lib/foo

submodule=$1

test -z "$submodule" && echo "submodule required" 1>&2 && exit 1
test ! -f .gitmodules && echo ".gitmodules file not found" 1>&2 && exit 2

name=$(echo "$submodule" | sed 's/\/$//g')

if [[ -z "$(git config --file=.gitmodules submodule."$name".url)" ]]; then
  echo "submodule not found" 1>&2
  exit 3
fi

git submodule deinit "$name"
git rm --cached "$name"
rm -rf .git/modules/"$name"
