#!/usr/bin/env bash

# git undo
#
# Usage:
#   git undo [STEPS]
#
# Hard-reset to HEAD's previous position (by default), or STEPS steps backward.
# Use `git undo [1]` to undo `git undo [STEPS]`.

set -e

usage() {
  grep '^#' < "$0" | tail -n +2 | cut -c 3-
}

step_size="${1:-1}"

if [[ ! $step_size =~ [[:digit:]]+ ]]; then
  usage
  exit 1
fi

head_posn="$(git rev-parse --abbrev-ref HEAD)"

git reset --hard "$head_posn@{$step_size}"
