" ----------------- Base Settings ------------------------
set nocompatible
filetype plugin indent on

" Don't display 'Pattern not found' messages
set shortmess+=c

" add fzf to rtp
set runtimepath+=~/.fzf

" ----------------- Load Plugins ------------------------

call plug#begin('~/.vim/plugged')
  source ~/.vim/plugged_manifest.vim
call plug#end()

" ---------------- Overrides  --------------------------

if filereadable('~/.vimrc.local')
  source $HOME/.vimrc.local
endif
