#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$HOME/.dotfiles/shell/env.sh"
source "$HOME/.env.secure.sh"

# [[ -f "$HOMEBREW_PREFIX/opt/asdf/asdf.sh" ]] && \
#     . "$HOMEBREW_PREFIX/opt/asdf/asdf.sh"

source "$HOME/.dotfiles/shell/path.sh"
