#!/bin/sh

# Generate or update ctags and save to .git directory

# Dependencies:
# Ctags -- Exuberant or Universal (preferred)
#
# Universal Ctags
# https://github.com/universal-ctags/ctags
#
# To install:
#   brew tap universal-ctags/universal-ctags
#   brew install --HEAD universal-ctags

dot_git_directory_location="$(git rev-parse --git-dir)"
project_root="$(git rev-parse --show-toplevel)"

ctags -f "$dot_git_directory_location/tags" -R "$project_root" &
