#!/bin/sh

# Generate or update ctags and save to .git directory
#
# Source: tpope
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

# Dependencies:
# Ctags -- Exuberant or Universal (preferred)
#
# Universal Ctags
# https://github.com/universal-ctags/ctags
#
# To install:
#   brew tap universal-ctags/universal-ctags
#   brew install --HEAD universal-ctags

set -e

git_dir="$(git rev-parse --git-dir)"

trap 'rm -f "$git_dir/$$.tags"' EXIT

git ls-files |\
  ctags --tag-relative \
  -L - \
  -f "$git_dir/$$.tags" \
  --languages=-javascript,sql

mv "$git_dir/$$.tags" "$git_dir/tags"
