#+TITLE: Emacs Config

* Notes
You do not need to run 'doom sync' after modifying this file!

Some additional useful functions/macros:

- =load!= for loading external *.el files relative to this one
- =use-package!= for configuring packages
- =after!= for running code after a package has loaded
- =add-load-path!= for adding directories to the =load-path=, relative to
  this file. Emacs searches the =load-path= when you load packages with
  =require= or =use-package=.
- =map!= for binding new keys

* Identity
Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets.

#+begin_src elisp
(setq user-full-name "Jake Romer"
      user-mail-address "jake@jmromer.org")
#+end_src

* Display
Doom exposes five (optional) variables for controlling fonts in Doom.
Here are the three important ones:

#+begin_src elisp
; `doom-big-font' -- used for `doom-big-font-mode': use this for presentations / streaming
(setq doom-font (font-spec :family "SF Mono" :size 16 :weight 'semi-light)
      doom-variable-pitch-font (font-spec :family "SF Mono" :size 16)
      doom-big-font (font-spec :family "SF Mono" :size 24))

(setq doom-theme 'doom-one)
(setq display-line-numbers-type 'relative)
(add-to-list 'initial-frame-alist '(fullscreen . maximized)) ;; Start maximized
#+end_src

* Data Locations
File paths for Org documents, Deft notes, and etc.

#+begin_src elisp
(setq org-directory (concat (getenv "XDG_DATA_HOME") "/org"))
(setq deft-directory (concat org-directory "/notes"))
#+end_src

* Keybindings
** dired
#+begin_src elisp
(map! :desc "Enter dired in the CWD of the current buffer's file." :n "-" #'dired-jump)
#+end_src

** magit
#+begin_src elisp
(map! :desc "Open magit" "s-g" #'magit-status)
#+end_src

* Package configuration functions
Define per-package configuration in functions to aid bisecting.

** company
** javascript
** markdown
** org
** python
** ruby
** snippets
** web

* Auxiliary functions
** yasnippet
#+begin_src elisp
(defun yas/camelcase-file-name ()
  "Camel-case the current buffer's file name."
  (interactive)
  (let ((filename
         (file-name-nondirectory (file-name-sans-extension
                                  (or (buffer-file-name)
                                      (buffer-name (current-buffer)))))))
    (mapconcat #'capitalize (split-string filename "[_\-]") "")))

(defun yas/strip (str)
  "Extract a parameter name from STR."
  (replace-regexp-in-string ":.*$" ""
   (replace-regexp-in-string "^\s+" ""
    (replace-regexp-in-string "," ""
     str))))

(defun yas/to-field-assignment (str)
  "Make 'STR' to 'self.`STR` = `STR`'."
  (format "self.%s = %s" (yas/strip str) (yas/strip str)))

(defun yas/prepend-colon (str)
  "Make `STR' to :`STR'."
  (format ":%s" (yas/strip str)))

(defun yas/indent-level ()
  "Determine the number of spaces the current line is indented."
  (interactive)
  (string-match "[^[:space:]]" (thing-at-point 'line t)))

(defun yas/indent-string ()
  "Return a string of spaces matching the current indentation level."
  (interactive)
  (make-string (yas/indent-level) ?\s))

(defun yas/indented-newline ()
  "Newline followed by correct indentation."
  (interactive)
  (format "\n%s" (yas/indent-string)))

(defun yas/args-list ()
  "Extract an args list from the current line."
  (interactive)
  (string-match "\(.+\)" (thing-at-point 'line t)))

(defun yas/to-ruby-accessors (str)
  "Splits STR into an `attr_accesor' statement."
  (interactive)
  (mapconcat 'yas/prepend-colon (split-string str ",") ", "))

(defun yas/to-ruby-setters (str)
  "Splits STR into a sequence of field assignments."
  (interactive)
  (mapconcat 'yas/to-field-assignment
             (split-string str ",")
             (yas/indented-newline)))
#+end_src
