#!/usr/bin/env bash

# Build p/d binary in local bin directory
# Generate initial project catalog file

set -e

if [[ -z "${XDG_DATA_HOME}" ]]; then
  echo "Error: XDG_DATA_HOME env var not set. Skipping p/d installation."
  exit 1
elif [[ -z "${DOTFILES_DIR}" ]]; then
  echo "Error: DOTFILES_DIR env var not set. Skipping p/d installation."
  exit 1
elif [[ -z "$(command -v mise)" ]]; then
  echo "Error: mise executable not found. Skipping p/d installation."
  exit 1
fi

builtin cd "${XDG_DATA_HOME}/pd"
eval "$(mise activate bash)"
mise use go

if [[ -z "$(command -v go)" ]]; then
  echo "Error: go executable not found. Skipping p/d installation."
  exit 1
fi

go get
go build -o ${DOTFILES_DIR}/bin/pd main.go
pd --pd-refresh &
