#!/usr/bin/env bash
#-------------------------------------------------------------
# Preamble
#-------------------------------------------------------------
LOCAL_DOTFILES="$HOME/.dotfiles"
SYNCED="$HOME/Dropbox/Sync"

function getc() {
  IFS= read -r -n1 -d '' "$@"
}

function step() {
  echo && echo "$1 ..."
}

#-------------------------------------------------------------
# Set up logging
#-------------------------------------------------------------
log_location="$HOME/Desktop/laptop.log"
touch $log_location

# pipe this whole script to tee
(
  step "Installing CLI tools, dotfiles, and Homebrew"

  # ===================================================

  step "Installing Xcode command line tools"

  loc="$(xcode-\select -p 2> /dev/null)"
  if [[ ! $loc =~ "CommandLineTools" ]]; then
    xcode-\select --install
    getc
  fi

  # ===================================================

  step "Cloning jkrmr/dotfiles"

  if [ ! -d $LOCAL_DOTFILES ]; then
    git clone --recursive https://github.com/jkrmr/dotfiles.git \
      $LOCAL_DOTFILES 1> /dev/null
  fi

  # ===================================================

  step "Installing or updating Homebrew"

  brew_installed="$(command -v brew >/dev/null)"
  if [[ -z "$brew_installed" ]]; then
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' |\
      ruby
  else
    brew update
  fi

  # ===================================================

  step "Installing Homebrew Cask"

  brew install caskroom/cask/brew-cask

  # ===================================================

  step "Installing Homebrew formulas"

  source "$HOME/.dotfiles/laptop/homebrew_packages.sh"

  # ===================================================

  step "Setting up Dropbox (press any key when complete)"

  brew cask install dropbox
  open $HOME/Applications/Dropbox.app
  getc

  # ===================================================

  step "Installing Rbenv, latest Ruby, RubyGems"

  eval "$(rbenv init - zsh)"

  ruby_version="$(curl -sSL http://ruby.thoughtbot.com/latest)"
  if ! rbenv versions | grep -Fq "$ruby_version"; then
    step "Installing Ruby $ruby_version"
    rbenv install -s "$ruby_version"
  fi

  rbenv global "$ruby_version"
  rbenv shell "$ruby_version"

  gem update --system

  # ===================================================

  step "Installing Bundler"

  gem install bundler
  gem update bundler

  # ===================================================

  step "Configuring Bundler"

  number_of_cores=$(sysctl -n hw.ncpu)
  bundle config --global jobs $((number_of_cores - 1))

  # ===================================================

  step "Linking OpenSSL, Installing libyaml"

  brew unlink openssl && brew link openssl --force
  brew install --force libyaml

  # ===================================================

  step "Accepting the Xcode CLI tools license"
  sudo xcodebuild -license

  step "Installing GNU tools"
  source "$HOME/.dotfiles/laptop/gnu_tools.sh"

  step "Installing Ruby, JS libraries"
  source "$HOME/.dotfiles/laptop/libraries.sh"

  step "Installing GUI apps with Homebrew Cask"
  source "$HOME/.dotfiles/laptop/homebrew_cask_packages.sh"

  step "Installing Package Packages"
  source "$HOME/.dotfiles/laptop/homebrew_package_sets.sh"

  # ==================================================

  step "Setting up LaunchAgents"

  mkdir -p ~/Library/LaunchAgents
  ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
  ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
  ln -sfv /usr/local/opt/emacs/*.plist ~/Library/LaunchAgents

  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.emacs.plist

  # ======================================================

  step "Setting homebrewed zsh as the default shell"

  source "$HOME/.zshrc"  # reload $PATH
  echo "$(which bash)" | sudo tee -a /etc/shells
  echo "$(which zsh)"  | sudo tee -a /etc/shells
  chsh -s $(which zsh)  # /usr/local/bin/zsh

  # ======================================================

  step "Linking dotfiles into home directory"

  env RCRC=$LOCAL_DOTFILES/rcrc rcup

  # ======================================================

  step "Linking remaining miscellaneous dotfiles"

  ln -sf $LOCAL_DOTFILES/default-gems    $HOME/.rbenv/default-gems
  ln -sf $LOCAL_DOTFILES/home/bin        $HOME/.bin
  ln -sf $LOCAL_DOTFILES/home/emacs.d    $HOME/.emacs.d
  ln -sf $LOCAL_DOTFILES/home/lein       $HOME/.lein
  ln -sf $LOCAL_DOTFILES/home/pry        $HOME/.pry
  ln -sf $LOCAL_DOTFILES/home/zsh        $HOME/.zsh
  ln -sf $LOCAL_DOTFILES/home/tmuxinator $HOME/.tmuxinator
  ln -sf $LOCAL_DOTFILES/home/vim        $HOME/.vim
  ln -sf $LOCAL_DOTFILES/home/bundle     $HOME/.bundle

  # ======================================================

  step "Linking to synced preference files"

  ln -sf $SYNCED/dotfiles/aws           $HOME/.aws
  ln -sf $SYNCED/dotfiles/env.secure.sh $HOME/.env.secure.sh
  ln -sf $SYNCED/dotfiles/exercism.json $HOME/.exercism.json
  ln -sf $SYNCED/Preferences/Firefox    $HOME/Library/Application\ Support
  ln -sf $SYNCED/Preferences/StickiesDatabase          $HOME/Library
  ln -sf $SYNCED/Preferences/com.jitouch.Jitouch.plist $HOME/Library/Preferences

  # ======================================================

  step "Creating and linking into ~/.ssh"

  mkdir $HOME/.ssh

  for file in id_rsa id_rsa.pub jkrmr-aws-usca.pem; do
    cp $SYNCED/dotfiles/$file  $HOME/.ssh
    chmod 700 $HOME/.ssh/$file
  done

  # ======================================================

  step "Setting Mac OS X defaults"

  source $LOCAL_DOTFILES/osx/set_defaults.sh

  # ======================================================

  # step "Enabling italics-compatible terminal profile"
  #
  # tic $LOCAL_DOTFILES/terminal/xterm-256color-italic.terminfo
  # tic $LOCAL_DOTFILES/terminal/screen-256color-italic.terminfo

  # ======================================================

  step "Installing Vim packages"

  vim +PlugUpdate +PlugClean! +qall

  # ======================================================

  step "Setup script is complete. Go install Xcode."

) | tee $log_location
